Add slide(draft) for hyunggun #25
devrel-kr/hacktoberfest-seoul pull request #31
Opened 2020-10-18 16:02 UTC by phg98

아직 초안입니다만, 일단 보냅니다.
의견이 있으면 알려주세요. ^^

2020-10-20 15:18 UTC, phg98 commented
거의 최종버전입니다. 내일 동영상 찍어보고 최종수정하면 될 듯 합니다. 그리고 다른 분들의 리뷰도 받으면 좋을텐데 다들 바쁘실듯하여 ㅠㅠ

2020-10-20 22:49 UTC, justinyoo requested changes
아앗, 깃헙에 올리실 파일은 .pdf 로 변환해서 올려주시면 좋습니다!

2020-10-21 01:19 UTC, phg98 commented
헉 그렇군요! 저녁에 올리겠습니다. 그런데 발표자료도 오픈할 계획이신지요?

2020-10-21 10:42 UTC, phg98 commented
pdf 파일을 올렸습니다.

2020-10-21 15:21 UTC, justinyoo approved these changes

2020-10-21 15:21 UTC, justinyoo commented
기본적으로는 발표자료를 공유할 예정입니다

2020-10-21 15:21 UTC, merged